services:
  uptime-kuma:
    build:
      context: .
      dockerfile: ./docker/dockerfile
      target: release
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
    networks:
      - dv-net

networks:
  dv-net:
    external: true
    name: main_dv-net
